/*
 * This file was automatically generated by EvoSuite
 * Fri May 22 12:03:33 GMT 2020
 */

package info.mywinecellar.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import info.mywinecellar.dto.SearchDto;
import info.mywinecellar.util.SearchSorter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SearchSorter_ESTest extends info.mywinecellar.util.SearchSorter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SearchSorter searchSorter0 = new SearchSorter();
      SearchDto.SearchResult searchDto_SearchResult0 = SearchDto.SearchResult.REGION;
      Long long0 = new Long(1495L);
      Double double0 = new Double(1.0);
      SearchDto searchDto0 = new SearchDto(searchDto_SearchResult0, long0, "", "", double0);
      SearchDto searchDto1 = new SearchDto(searchDto_SearchResult0, long0, "L14Xwhmxc3", "SearchDto(type=REGION, id=1495, name=, description=, rank=1.0)", double0);
      int int0 = searchSorter0.compare(searchDto0, searchDto1);
      assertEquals((-10), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SearchSorter searchSorter0 = new SearchSorter();
      SearchDto.SearchResult searchDto_SearchResult0 = SearchDto.SearchResult.REGION;
      Long long0 = new Long(1L);
      Double double0 = Double.valueOf((double) 1L);
      SearchDto searchDto0 = new SearchDto(searchDto_SearchResult0, long0, "J%Z9&", "2J^)", double0);
      Double double1 = new Double(0);
      SearchDto searchDto1 = new SearchDto(searchDto_SearchResult0, long0, "2J^)", "{", double1);
      int int0 = searchSorter0.compare(searchDto1, searchDto0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SearchSorter searchSorter0 = new SearchSorter();
      SearchDto.SearchResult searchDto_SearchResult0 = SearchDto.SearchResult.PRODUCER;
      Long long0 = new Long(1585L);
      Double double0 = new Double(1585L);
      SearchDto searchDto0 = new SearchDto(searchDto_SearchResult0, long0, (String) null, (String) null, double0);
      // Undeclared exception!
      try { 
        searchSorter0.compare(searchDto0, searchDto0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("info.mywinecellar.util.SearchSorter", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SearchSorter searchSorter0 = new SearchSorter();
      SearchDto.SearchResult searchDto_SearchResult0 = SearchDto.SearchResult.REGION;
      Long long0 = new Long(1L);
      Double double0 = Double.valueOf((double) 1L);
      SearchDto searchDto0 = new SearchDto(searchDto_SearchResult0, long0, "J%Z9&", "2J^)", double0);
      Double double1 = new Double(0);
      SearchDto searchDto1 = new SearchDto(searchDto_SearchResult0, long0, "2J^)", "{", double1);
      int int0 = searchSorter0.compare(searchDto0, searchDto1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SearchSorter searchSorter0 = new SearchSorter();
      SearchDto.SearchResult searchDto_SearchResult0 = SearchDto.SearchResult.AREA;
      Long long0 = new Long(2556L);
      Double double0 = new Double(2556L);
      SearchDto searchDto0 = new SearchDto(searchDto_SearchResult0, long0, "Y=$7~dg 1!zmm]ua", "!*V", double0);
      int int0 = searchSorter0.compare(searchDto0, searchDto0);
      assertEquals(0, int0);
  }
}
