INSERT INTO authority (id,authority) VALUES (1,'ROLE_ADMIN');
INSERT INTO authority (id,authority) VALUES (2,'ROLE_USER');

INSERT INTO users (id, enabled, username, password) VALUES ( 999999, true, 'admin', '$2a$10$FQvwDTU8onTZ74SJy1N2zOLAeIC5em9ETr5ggcPS9/Ne/S4WXM2zG');

INSERT INTO user_authority (authority_id, user_id) VALUES ( 1, 999999 );

INSERT INTO users (id, enabled, username, password) VALUES ( 888888, true, 'user', '$2a$10$FQvwDTU8onTZ74SJy1N2zOLAeIC5em9ETr5ggcPS9/Ne/S4WXM2zG');

INSERT INTO user_authority (authority_id, user_id) VALUES ( 2, 888888 );

INSERT INTO country (name, description) VALUES ('Afghanistan', '');
INSERT INTO country (name, description) VALUES ('Albania', '');
INSERT INTO country (name, description) VALUES ('Algeria', '');
INSERT INTO country (name, description) VALUES ('Andorra', '');
INSERT INTO country (name, description) VALUES ('Angola', '');
INSERT INTO country (name, description) VALUES ('Antigua and Barbuda', '');
INSERT INTO country (name, description) VALUES ('Argentina', '');
INSERT INTO country (name, description) VALUES ('Armenia', '');
INSERT INTO country (name, description) VALUES ('Australia', '');
INSERT INTO country (name, description) VALUES ('Austria', '');
INSERT INTO country (name, description) VALUES ('Azerbaijan', '');
INSERT INTO country (name, description) VALUES ('The Bahamas', '');
INSERT INTO country (name, description) VALUES ('Bahrain', '');
INSERT INTO country (name, description) VALUES ('Bangladesh', '');
INSERT INTO country (name, description) VALUES ('Barbados', '');
INSERT INTO country (name, description) VALUES ('Belarus', '');
INSERT INTO country (name, description) VALUES ('Belgium', '');
INSERT INTO country (name, description) VALUES ('Belize', '');
INSERT INTO country (name, description) VALUES ('Benin', '');
INSERT INTO country (name, description) VALUES ('Bhutan', '');
INSERT INTO country (name, description) VALUES ('Bolivia', '');
INSERT INTO country (name, description) VALUES ('Bosnia and Herzegovina', '');
INSERT INTO country (name, description) VALUES ('Botswana', '');
INSERT INTO country (name, description) VALUES ('Brazil', '');
INSERT INTO country (name, description) VALUES ('Brunei', '');
INSERT INTO country (name, description) VALUES ('Bulgaria', '');
INSERT INTO country (name, description) VALUES ('Burkina Faso', '');
INSERT INTO country (name, description) VALUES ('Burundi', '');
INSERT INTO country (name, description) VALUES ('Cabo Verde', '');
INSERT INTO country (name, description) VALUES ('Cambodia', '');
INSERT INTO country (name, description) VALUES ('Cameroon', '');
INSERT INTO country (name, description) VALUES ('Canada', '');
INSERT INTO country (name, description) VALUES ('Central African Republic', '');
INSERT INTO country (name, description) VALUES ('Chad', '');
INSERT INTO country (name, description) VALUES ('Chile', '');
INSERT INTO country (name, description) VALUES ('China', '');
INSERT INTO country (name, description) VALUES ('Colombia', '');
INSERT INTO country (name, description) VALUES ('Comoros', '');
INSERT INTO country (name, description) VALUES ('Congo, Democratic Republic of the', '');
INSERT INTO country (name, description) VALUES ('Costa Rica', '');
INSERT INTO country (name, description) VALUES ('Côte d’Ivoire', '');
INSERT INTO country (name, description) VALUES ('Croatia', '');
INSERT INTO country (name, description) VALUES ('Cuba', '');
INSERT INTO country (name, description) VALUES ('Cyprus', '');
INSERT INTO country (name, description) VALUES ('Czech Republic', '');
INSERT INTO country (name, description) VALUES ('Denmark', '');
INSERT INTO country (name, description) VALUES ('Djibouti', '');
INSERT INTO country (name, description) VALUES ('Dominica', '');
INSERT INTO country (name, description) VALUES ('Dominican Republic', '');
INSERT INTO country (name, description) VALUES ('East Timor', '');
INSERT INTO country (name, description) VALUES ('Ecuador', '');
INSERT INTO country (name, description) VALUES ('Egypt', '');
INSERT INTO country (name, description) VALUES ('El Salvador', '');
INSERT INTO country (name, description) VALUES ('Equatorial Guinea', '');
INSERT INTO country (name, description) VALUES ('Eritrea', '');
INSERT INTO country (name, description) VALUES ('Estonia', '');
INSERT INTO country (name, description) VALUES ('Eswatini', '');
INSERT INTO country (name, description) VALUES ('Ethiopia', '');
INSERT INTO country (name, description) VALUES ('Fiji', '');
INSERT INTO country (name, description) VALUES ('Finland', '');
INSERT INTO country (name, description) VALUES ('France', '');
INSERT INTO country (name, description) VALUES ('Gabon', '');
INSERT INTO country (name, description) VALUES ('The Gambia', '');
INSERT INTO country (name, description) VALUES ('Georgia', '');
INSERT INTO country (name, description) VALUES ('Germany', '');
INSERT INTO country (name, description) VALUES ('Ghana', '');
INSERT INTO country (name, description) VALUES ('Greece', '');
INSERT INTO country (name, description) VALUES ('Grenada', '');
INSERT INTO country (name, description) VALUES ('Guatemala', '');
INSERT INTO country (name, description) VALUES ('Guinea', '');
INSERT INTO country (name, description) VALUES ('Guinea-Bissau', '');
INSERT INTO country (name, description) VALUES ('Guyana', '');
INSERT INTO country (name, description) VALUES ('Haiti', '');
INSERT INTO country (name, description) VALUES ('Honduras', '');
INSERT INTO country (name, description) VALUES ('Hungary', '');
INSERT INTO country (name, description) VALUES ('Iceland', '');
INSERT INTO country (name, description) VALUES ('India', '');
INSERT INTO country (name, description) VALUES ('Indonesia', '');
INSERT INTO country (name, description) VALUES ('Iran', '');
INSERT INTO country (name, description) VALUES ('Iraq', '');
INSERT INTO country (name, description) VALUES ('Ireland', '');
INSERT INTO country (name, description) VALUES ('Israel', '');
INSERT INTO country (name, description) VALUES ('Italy', '');
INSERT INTO country (name, description) VALUES ('Jamaica', '');
INSERT INTO country (name, description) VALUES ('Japan', '');
INSERT INTO country (name, description) VALUES ('Jordan', '');
INSERT INTO country (name, description) VALUES ('Kazakhstan', '');
INSERT INTO country (name, description) VALUES ('Kenya', '');
INSERT INTO country (name, description) VALUES ('Kiribati', '');
INSERT INTO country (name, description) VALUES ('Korea North', '');
INSERT INTO country (name, description) VALUES ('Korea South', '');
INSERT INTO country (name, description) VALUES ('Kosovo', '');
INSERT INTO country (name, description) VALUES ('Kuwait', '');
INSERT INTO country (name, description) VALUES ('Kyrgyzstan', '');
INSERT INTO country (name, description) VALUES ('Laos', '');
INSERT INTO country (name, description) VALUES ('Latvia', '');
INSERT INTO country (name, description) VALUES ('Lebanon', '');
INSERT INTO country (name, description) VALUES ('Lesotho', '');
INSERT INTO country (name, description) VALUES ('Liberia', '');
INSERT INTO country (name, description) VALUES ('Libya', '');
INSERT INTO country (name, description) VALUES ('Liechtenstein', '');
INSERT INTO country (name, description) VALUES ('Lithuania', '');
INSERT INTO country (name, description) VALUES ('Luxembourg', '');
INSERT INTO country (name, description) VALUES ('Madagascar', '');
INSERT INTO country (name, description) VALUES ('Malawi', '');
INSERT INTO country (name, description) VALUES ('Malaysia', '');
INSERT INTO country (name, description) VALUES ('Maldives', '');
INSERT INTO country (name, description) VALUES ('Mali', '');
INSERT INTO country (name, description) VALUES ('Malta', '');
INSERT INTO country (name, description) VALUES ('Marshall Islands', '');
INSERT INTO country (name, description) VALUES ('Mauritania', '');
INSERT INTO country (name, description) VALUES ('Mauritius', '');
INSERT INTO country (name, description) VALUES ('Mexico', '');
INSERT INTO country (name, description) VALUES ('Micronesia, Federated States of', '');
INSERT INTO country (name, description) VALUES ('Moldova', '');
INSERT INTO country (name, description) VALUES ('Monaco', '');
INSERT INTO country (name, description) VALUES ('Mongolia', '');
INSERT INTO country (name, description) VALUES ('Montenegro', '');
INSERT INTO country (name, description) VALUES ('Morocco', '');
INSERT INTO country (name, description) VALUES ('Mozambique', '');
INSERT INTO country (name, description) VALUES ('Myanmar (Burma)', '');
INSERT INTO country (name, description) VALUES ('Namibia', '');
INSERT INTO country (name, description) VALUES ('Nauru', '');
INSERT INTO country (name, description) VALUES ('Nepal', '');
INSERT INTO country (name, description) VALUES ('Netherlands', '');
INSERT INTO country (name, description) VALUES ('New Zealand', '');
INSERT INTO country (name, description) VALUES ('Nicaragua', '');
INSERT INTO country (name, description) VALUES ('Niger', '');
INSERT INTO country (name, description) VALUES ('Nigeria', '');
INSERT INTO country (name, description) VALUES ('North Macedonia', '');
INSERT INTO country (name, description) VALUES ('Norway', '');
INSERT INTO country (name, description) VALUES ('Oman', '');
INSERT INTO country (name, description) VALUES ('Pakistan', '');
INSERT INTO country (name, description) VALUES ('Palau', '');
INSERT INTO country (name, description) VALUES ('Panama', '');
INSERT INTO country (name, description) VALUES ('Papua New Guinea', '');
INSERT INTO country (name, description) VALUES ('Paraguay', '');
INSERT INTO country (name, description) VALUES ('Peru', '');
INSERT INTO country (name, description) VALUES ('Philippines', '');
INSERT INTO country (name, description) VALUES ('Poland', '');
INSERT INTO country (name, description) VALUES ('Portugal', '');
INSERT INTO country (name, description) VALUES ('Qatar', '');
INSERT INTO country (name, description) VALUES ('Romania', '');
INSERT INTO country (name, description) VALUES ('Russia', '');
INSERT INTO country (name, description) VALUES ('Rwanda', '');
INSERT INTO country (name, description) VALUES ('Saint Kitts and Nevis', '');
INSERT INTO country (name, description) VALUES ('Saint Lucia', '');
INSERT INTO country (name, description) VALUES ('Saint Vincent and the Grenadines', '');
INSERT INTO country (name, description) VALUES ('Samoa', '');
INSERT INTO country (name, description) VALUES ('San Marino', '');
INSERT INTO country (name, description) VALUES ('Sao Tome and Principe', '');
INSERT INTO country (name, description) VALUES ('Saudi Arabia', '');
INSERT INTO country (name, description) VALUES ('Senegal', '');
INSERT INTO country (name, description) VALUES ('Serbia', '');
INSERT INTO country (name, description) VALUES ('Seychelles', '');
INSERT INTO country (name, description) VALUES ('Sierra Leone', '');
INSERT INTO country (name, description) VALUES ('Singapore', '');
INSERT INTO country (name, description) VALUES ('Slovakia', '');
INSERT INTO country (name, description) VALUES ('Slovenia', '');
INSERT INTO country (name, description) VALUES ('Solomon Islands', '');
INSERT INTO country (name, description) VALUES ('Somalia', '');
INSERT INTO country (name, description) VALUES ('South Africa', '');
INSERT INTO country (name, description) VALUES ('Spain', '');
INSERT INTO country (name, description) VALUES ('Sri Lanka', '');
INSERT INTO country (name, description) VALUES ('Sudan', '');
INSERT INTO country (name, description) VALUES ('Suriname', '');
INSERT INTO country (name, description) VALUES ('Sweden', '');
INSERT INTO country (name, description) VALUES ('Switzerland', '');
INSERT INTO country (name, description) VALUES ('Syria', '');
INSERT INTO country (name, description) VALUES ('Taiwan', '');
INSERT INTO country (name, description) VALUES ('Tajikistan', '');
INSERT INTO country (name, description) VALUES ('Tanzania', '');
INSERT INTO country (name, description) VALUES ('Thailand', '');
INSERT INTO country (name, description) VALUES ('Togo', '');
INSERT INTO country (name, description) VALUES ('Tonga', '');
INSERT INTO country (name, description) VALUES ('Trinidad and Tobago', '');
INSERT INTO country (name, description) VALUES ('Tunisia', '');
INSERT INTO country (name, description) VALUES ('Turkey', '');
INSERT INTO country (name, description) VALUES ('Turkmenistan', '');
INSERT INTO country (name, description) VALUES ('Tuvalu', '');
INSERT INTO country (name, description) VALUES ('Uganda', '');
INSERT INTO country (name, description) VALUES ('Ukraine', '');
INSERT INTO country (name, description) VALUES ('United Arab Emirates', '');
INSERT INTO country (name, description) VALUES ('United Kingdom', '');
INSERT INTO country (name, description) VALUES ('United States', '');
INSERT INTO country (name, description) VALUES ('Uruguay', '');
INSERT INTO country (name, description) VALUES ('Uzbekistan', '');
INSERT INTO country (name, description) VALUES ('Vanuatu', '');
INSERT INTO country (name, description) VALUES ('Vatican City', '');
INSERT INTO country (name, description) VALUES ('Venezuela', '');
INSERT INTO country (name, description) VALUES ('Vietnam', '');
INSERT INTO country (name, description) VALUES ('Yemen', '');
INSERT INTO country (name, description) VALUES ('Zambia', '');
INSERT INTO country (name, description) VALUES ('Zimbabwe', '');
