INSERT INTO barrel (name, description, weblink) VALUES ('French (New)', '', '');
INSERT INTO barrel (name, description, weblink) VALUES ('French (Used)', '', '');
INSERT INTO barrel (name, description, weblink) VALUES ('American (New)', '', '');
INSERT INTO barrel (name, description, weblink) VALUES ('American (Used)', '', '');
INSERT INTO barrel (name, description, weblink) VALUES ('Slavonian (New)', '', '');
INSERT INTO barrel (name, description, weblink) VALUES ('Slavonian (Used)', '', '');
INSERT INTO barrel (name, description, weblink) VALUES ('Steel', '', '');
INSERT INTO barrel (name, description, weblink) VALUES ('Concrete', '', '');
INSERT INTO barrel (name, description, weblink) VALUES ('Chips', '', '');
INSERT INTO barrel (name, description, weblink) VALUES ('Staves', '', '');
