INSERT INTO country (name, flag, description, weblink) VALUES ('Afghanistan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Albania', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Algeria', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Andorra', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Angola', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Antigua and Barbuda', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Argentina', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Armenia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Australia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Austria', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Azerbaijan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('The Bahamas', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Bahrain', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Bangladesh', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Barbados', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Belarus', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Belgium', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Belize', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Benin', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Bhutan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Bolivia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Bosnia and Herzegovina', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Botswana', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Brazil', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Brunei', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Bulgaria', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Burkina Faso', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Burundi', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Cabo Verde', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Cambodia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Cameroon', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Canada', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Central African Republic', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Chad', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Chile', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('China', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Colombia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Comoros', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Congo, Democratic Republic of the', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Costa Rica', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Côte d’Ivoire', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Croatia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Cuba', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Cyprus', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Czech Republic', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Denmark', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Djibouti', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Dominica', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Dominican Republic', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('East Timor', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Ecuador', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Egypt', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('El Salvador', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Equatorial Guinea', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Eritrea', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Estonia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Eswatini', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Ethiopia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Fiji', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Finland', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('France', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Gabon', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('The Gambia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Georgia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Germany', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Ghana', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Greece', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Grenada', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Guatemala', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Guinea', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Guinea-Bissau', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Guyana', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Haiti', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Honduras', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Hungary', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Iceland', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('India', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Indonesia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Iran', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Iraq', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Ireland', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Israel', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Italy', 'it', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Jamaica', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Japan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Jordan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Kazakhstan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Kenya', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Kiribati', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Korea North', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Korea South', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Kosovo', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Kuwait', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Kyrgyzstan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Laos', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Latvia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Lebanon', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Lesotho', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Liberia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Libya', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Liechtenstein', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Lithuania', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Luxembourg', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Madagascar', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Malawi', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Malaysia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Maldives', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Mali', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Malta', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Marshall Islands', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Mauritania', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Mauritius', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Mexico', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Micronesia, Federated States of', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Moldova', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Monaco', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Mongolia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Montenegro', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Morocco', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Mozambique', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Myanmar (Burma)', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Namibia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Nauru', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Nepal', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Netherlands', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('New Zealand', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Nicaragua', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Niger', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Nigeria', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('North Macedonia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Norway', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Oman', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Pakistan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Palau', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Panama', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Papua New Guinea', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Paraguay', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Peru', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Philippines', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Poland', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Portugal', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Qatar', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Romania', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Russia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Rwanda', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Saint Kitts and Nevis', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Saint Lucia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Saint Vincent and the Grenadines', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Samoa', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('San Marino', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Sao Tome and Principe', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Saudi Arabia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Senegal', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Serbia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Seychelles', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Sierra Leone', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Singapore', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Slovakia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Slovenia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Solomon Islands', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Somalia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('South Africa', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Spain', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Sri Lanka', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Sudan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Suriname', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Sweden', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Switzerland', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Syria', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Taiwan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Tajikistan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Tanzania', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Thailand', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Togo', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Tonga', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Trinidad and Tobago', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Tunisia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Turkey', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Turkmenistan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Tuvalu', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Uganda', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Ukraine', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('United Arab Emirates', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('United Kingdom', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('United States', 'us', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Uruguay', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Uzbekistan', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Vanuatu', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Vatican City', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Venezuela', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Vietnam', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Yemen', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Zambia', '', '', '');
INSERT INTO country (name, flag, description, weblink) VALUES ('Zimbabwe', '', '', '');
