-- Italy/Region
INSERT INTO region (name, description, weblink, country_id) VALUES ('Abruzzo', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Basilicata', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Calabria', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Campania', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Emilia Romagna', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Friuli-Venezia Giulia', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Lazio', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Liguria', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Lombardy', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Marche', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Molise', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Piedmont', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Puglia', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Sardinia', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Sicily', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Tuscany', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Trentino-Alto Adige', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Umbria', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Valle d’Aosta', '', '', 83);
INSERT INTO region (name, description, weblink, country_id) VALUES ('Veneto', '', '', 83);

-- Italy/Abruzzo
INSERT INTO area (name, description, weblink) VALUES ('Abruzzo', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Abruzzo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cerasuolo d’Abruzzo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Aprutini IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli del Sangro IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colline Frentane IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colline Pescaresi IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colline Teatine IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colline Teramane Montepulciano d’Abruzzo DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Controguerra DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Del Vastese / Histonium IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montepulciano d’Abruzzo Colline Teramane DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montepulciano d’Abruzzo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ortona DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre Aquilane / Terre de L’Aquila IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre Tollesi / Tullum DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre di Chieti IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Trebbiano d’Abruzzo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Villamagna DOC ', '', '');
INSERT INTO region_area (SELECT 51, i FROM generate_series(279, 297) as i);

-- Italy/Basilicata
INSERT INTO area (name, description, weblink) VALUES ('Basilicata', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Aglianico del Vulture DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Aglianico del Vulture Superiore DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Basilicata IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Grottino di Roccanova DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Matera DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre dell’Alta Val d’Agri DOC', '', '');
INSERT INTO region_area (SELECT 52, i FROM generate_series(298, 304) as i);

-- Italy/Calabria
INSERT INTO area (name, description, weblink) VALUES ('Calabria', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bivongi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cirò DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Greco di Bianco DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Arghillà IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Calabria IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Costa Viola IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lipuda IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Locride IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Palizzi IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Pellaro IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Scilla IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Val di Neto IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valdamato IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lamezia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Melissa DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('S. Anna di Isola Capo Rizzuto DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Savuto DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Scavigna DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre di Cosenza DOC', '', '');
INSERT INTO region_area (SELECT 53, i FROM generate_series(305, 324) as i);

-- Italy/Campania
INSERT INTO area (name, description, weblink) VALUES ('Campania', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Aglianico del Taburno DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Aversa DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Benevento / Beneventano IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Campania IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Campi Flegrei DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Capri DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Casavecchia di Pontelatone DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Castel San Lorenzo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Catalanesca del Monte Somma IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cilento DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli di Salerno IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Costa d’Amalfi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Dugenta IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Epomeo IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Falanghina del Sannio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Falerno del Massico DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Fiano di Avellino DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Galluccio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Greco di Tufo DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Irpinia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ischia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Paestum IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Penisola Sorrentina DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Pompeiano IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Roccamonfina IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sannio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Taurasi DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre del Volturno IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vesuvio DOC', '', '');
INSERT INTO region_area (SELECT 54, i FROM generate_series(325, 354) as i);

-- Italy/Emilia Romagna
INSERT INTO area (name, description, weblink) VALUES ('Emilia Romagna', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bosco Eliceo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Castelfranco Emilia IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Bolognesi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Bolognesi Pignoletto DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Piacentini DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Romagna Centrale DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli di Faenza DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli di Parma DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli di Rimini DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli di Scandiano e di Canossa DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli d’Imola DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Emilia / dell’Emilia IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Forlì IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Fortana del Taro IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Gutturnio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lambrusco Grasparossa di Castelvetro DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lambrusco Salamino di Santa Croce DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lambrusco di Sorbara DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Modena DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ortrugo dei Colli Piacentini DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Pignoletto DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ravenna IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Reggiano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Reno DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Romagna Albana DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Romagna DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Rubicone IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sillaro / Bianco del Sillaro IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre di Veleja IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Val Tidone IGT', '', '');
INSERT INTO region_area (SELECT 55, i FROM generate_series(355, 385) as i);

-- Italy/Friuli-Venezia Giulia
INSERT INTO area (name, description, weblink) VALUES ('Friuli-Venezia Giulia', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Alto Livenza IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Carso / Carso-Kras DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Orientali del Friuli Picolit DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Collio Goriziano / Collio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Delle Venezie DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Delle Venezie IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Friuli / Friuli Venezia Giulia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Friuli Annia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Friuli Aquileia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Friuli Colli Orientali DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Friuli Grave DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Friuli Isonzo / Isonzo del Friuli DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Friuli Latisana DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lison DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lison-Pramaggiore DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Prosecco DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ramandolo DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Rosazzo DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Trevenezie IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Venezia Giulia IGT', '', '');
INSERT INTO region_area (SELECT 56, i FROM generate_series(386, 406) as i);

-- Italy/Lazio
INSERT INTO area (name, description, weblink) VALUES ('Lazio', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Aleatico di Gradoli DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Anagni IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Aprilia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Atina DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bianco Capena DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cannellino di Frascati DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Castelli Romani DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cerveteri DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cesanese del Piglio / Piglio DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cesanese di Affile / Affile DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cesanese di Olevano Romano / Olevano Romano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Circeo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Civitella d’Agliano IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Albani DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Cimini IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Etruschi Viterbesi / Tuscia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Lanuvini DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli della Sabina DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cori DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Costa Etrusco Romana IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Est! Est!! Est!!! di Montefiascone DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Frascati DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Frascati Superiore DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Frusinate / del Frusinate IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Genazzano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lazio IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Marino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montecompatri-Colonna / Montecompatri / Colonna DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Nettuno DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Orvieto DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Roma DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Tarquinia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terracina / Moscato di Terracina DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Velletri DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vignanello DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Zagarolo DOC', '', '');
INSERT INTO region_area (SELECT 57, i FROM generate_series(407, 443) as i);

-- Italy/Liguria
INSERT INTO area (name, description, weblink) VALUES ('Liguria', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cinque Terre / Cinque Terre Sciacchetrà DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli di Luni DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colline Savonesi IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colline del Genovesato IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colline di Levanto DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Golfo del Tigullio–Portofino / Portofino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Liguria di Levante IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Pornassio / Ormeasco di Pornassio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Riviera Ligure di Ponente DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Rossese di Dolceacqua / Dolceacqua DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terrazze dell’Imperiese IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Val Polcèvera DOC', '', '');
INSERT INTO region_area (SELECT 58, i FROM generate_series(444, 456) as i);

-- Italy/Lombardy
INSERT INTO area (name, description, weblink) VALUES ('Lombardy', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Alpi Retiche IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Alto Mincio IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Benaco Bresciano IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bergamasca IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bonarda dell’Oltrepò Pavese DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Botticino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Buttafuoco dell’Oltrepò Pavese / Buttafuoco DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Capriano del Colle DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Casteggio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cellatica DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Collina del Milanese IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Curtefranca DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Franciacorta DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Garda Colli Mantovani DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Garda DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lambrusco Mantovano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lugana DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montenetto di Brescia IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Oltrepò Pavese DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Oltrepò Pavese Metodo Classico DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Oltrepò Pavese Pinot Grigio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Pinot Nero dell’Oltrepò Pavese DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Provincia di Mantova IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Provincia di Pavia IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Quistello IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Riviera del Garda Bresciano / Garda Bresciano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Riviera del Garda Classico DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ronchi Varesini IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ronchi di Brescia IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sabbioneta IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('San Colombano al Lambro / San Colombano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('San Martino della Battaglia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sangue di Giuda dell’Oltrepò Pavese / Sangue di Giuda DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Scanzo / Moscato di Scanzo DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sebino IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sforzato di Valtellina / Sfursat di Valtellina DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terrazze Retiche di Sondrio IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre Lariane IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre del Colleoni / Colleoni DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valcalepio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valcamonica IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valtellina Rosso / Rosso di Valtellina DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valtellina Superiore DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valtènesi DOC', '', '');
INSERT INTO region_area (SELECT 59, i FROM generate_series(457, 501) as i);

-- Italy/Marche
INSERT INTO area (name, description, weblink) VALUES ('Marche', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bianchello del Metauro DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Castelli di Jesi Verdicchio Riserva DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Maceratesi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Pesaresi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cònero DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Esino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Falerio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('I Terreni di Sanseverino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lacrima di Morro / Lacrima di Morro d’Alba DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Marche IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Offida DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Pergola DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Rosso Cònero DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Rosso Piceno / Piceno DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('San Ginesio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Serrapetrona DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre di Offida DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Verdicchio dei Castelli di Jesi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Verdicchio di Matelica DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Verdicchio di Matelica Riserva DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vernaccia di Serrapetrona DOCG', '', '');
INSERT INTO region_area (SELECT 60, i FROM generate_series(502, 523) as i);

-- Italy/Molise
INSERT INTO area (name, description, weblink) VALUES ('Molise', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Biferno DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Molise DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Osco / Terre degli Osci IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Pentro di Isernia / Pentro DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Rotae IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Tintilia del Molise DOC', '', '');
INSERT INTO region_area (SELECT 61, i FROM generate_series(524, 530) as i);

-- Italy/Piedmont
INSERT INTO area (name, description, weblink) VALUES ('Piedmont', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Alba DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Albugnano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Alta Langa DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Asti DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Barbaresco DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Barbera d’Alba DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Barbera d’Asti DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Barbera del Monferrato DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Barbera del Monferrato Superiore DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Barolo DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Boca DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Brachetto d’Acqui / Acqui DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bramaterra DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Calosso DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Canavese DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Carema DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cisterna d’Asti DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Tortonesi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Collina Torinese DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colline Novaresi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colline Saluzzesi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cortese dell’Alto Monferrato DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Coste della Sesia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Dogliani DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Dolcetto d’Acqui DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Dolcetto d’Alba DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Dolcetto d’Asti DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Dolcetto di Diano d’Alba / Diano d’Alba DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Dolcetto di Ovada DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Dolcetto di Ovada Superiore / Ovada DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Erbaluce di Caluso / Caluso DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Fara DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Freisa d’Asti DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Freisa di Chieri DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Gabiano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Gattinara DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Gavi / Cortese di Gavi DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ghemme DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Grignolino d’Asti DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Grignolino del Monferrato Casalese DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Langhe DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lessona DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Loazzolo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Malvasia di Casorzo d’Asti / Malvasia di Casorzo / Casorzo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Malvasia di Castelnuovo Don Bosco DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Monferrato DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Nebbiolo d’Alba DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Nizza DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Piemonte DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Pinerolese DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Roero DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Rubino di Cantavenna DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ruchè di Castagnole Monferrato DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sizzano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Strevi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre Alfieri DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valli Ossolane DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valsusa DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Verduno Pelaverga / Verduno DOC', '', '');
INSERT INTO region_area (SELECT 62, i FROM generate_series(531, 590) as i);

-- Italy/Puglia
INSERT INTO area (name, description, weblink) VALUES ('Puglia', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Aleatico di Puglia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Alezio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Barletta DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Brindisi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cacc’è Mmitte di Lucera DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Castel del Monte Bombino Nero DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Castel del Monte DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Castel del Monte Nero di Troia Riserva DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Castel del Monte Rosso Riserva DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colline Joniche Tarantine DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Copertino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Daunia IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Galatina DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Gioia del Colle DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Gravina DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Leverano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lizzano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Locorotondo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Martina / Martina Franca DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Matino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Moscato di Trani DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Murgia IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Nardò DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Negroamaro di Terra d’Otranto DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Orta Nova DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ostuni DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Primitivo di Manduria DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Primitivo di Manduria Dolce Naturale DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Puglia IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Rosso di Cerignola DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Salento IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Salice Salentino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('San Severo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Squinzano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Tarantino IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Tavoliere delle Puglie / Tavoliere DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terra d’Otranto DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valle d’Itria IGT', '', '');
INSERT INTO region_area (SELECT 63, i FROM generate_series(591, 629) as i);

-- Italy/Sardinia
INSERT INTO area (name, description, weblink) VALUES ('Sardinia', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Alghero DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Arborea DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Barbagia IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cagliari DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Campidano di Terralba / Terralba DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cannonau di Sardegna DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Carignano del Sulcis DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli del Limbara IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Girò di Cagliari DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Isola dei Nuraghi IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Malvasia di Bosa DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Mandrolisai DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Marmilla IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Monica di Sardegna DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Moscato di Sardegna DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Moscato di Sorso-Sennori / Moscato di Sennori / Moscato di Sorso DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Nasco di Cagliari DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Nuragus di Cagliari DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Nurra IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ogliastra IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Parteolla IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Planargia IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Provincia di Nuoro IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Romangia IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sardegna Semidano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sibiola IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Tharros IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Trexenta IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valle del Tirso IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valli di Porto Pino IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vermentino di Gallura DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vermentino di Sardegna DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vernaccia di Oristano DOC', '', '');
INSERT INTO region_area (SELECT 64, i FROM generate_series(630, 663) as i);

-- Italy/Sicily
INSERT INTO area (name, description, weblink) VALUES ('Sicily', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Alcamo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Avola IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Camarro IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cerasuolo di Vittoria DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Contea di Sclafani / Valledolmo–Contea di Sclafani DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Contessa Entellina DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Delia Nivolelli DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Eloro DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Erice DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Etna DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Faro DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Fontanarossa di Cerda IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Malvasia delle Lipari DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Mamertino di Milazzo / Mamertino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Marsala DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Menfi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Monreale DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Noto DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Pantelleria DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Riesi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Salaparuta DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Salemi IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Salina IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sambuca di Sicilia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Santa Margherita di Belice DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sciacca DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sicilia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Siracusa DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre Siciliane IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valle Belice IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vittoria DOC', '', '');
INSERT INTO region_area (SELECT 65, i FROM generate_series(664, 695) as i);

-- Italy/Tuscany
INSERT INTO area (name, description, weblink) VALUES ('Tuscany', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Alta Valle della Greve IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Ansonica Costa dell’Argentario DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Barco Reale di Carmignano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bianco dell’Empolese DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bianco di Pitigliano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bolgheri DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bolgheri Sassicaia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Brunello di Montalcino DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Candia dei Colli Apuani DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Capalbio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Carmignano DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Chianti Classico DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Chianti DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli della Toscana Centrale IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli dell’Etruria Centrale DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli di Luni DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colline Lucchesi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cortona DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Costa Toscana IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Elba Aleatico Passito / Aleatico Passito dell’Elba DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Elba DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Grance Senesi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Maremma Toscana DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montecarlo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montecastelli IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montecucco DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montecucco Sangiovese DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Monteregio di Massa Marittima DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montescudaio DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Morellino di Scansano DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Moscadello di Montalcino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Orcia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Parrina DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Pomino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Rosso di Montalcino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Rosso di Montepulciano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('San Gimignano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('San Torpè DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sant’Antimo DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Sovana DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Suvereto DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terratico di Bibbona DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre di Casole DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Terre di Pisa DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Toscano / Toscana IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Val di Cornia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Val di Cornia Rosso / Rosso della Val di Cornia DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Val di Magra IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Val d’Arbia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Val d’Arno di Sopra / Valdarno di Sopra DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valdichiana Toscana DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valdinievole DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vernaccia di San Gimignano DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vin Santo del Chianti Classico DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vin Santo del Chianti DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vin Santo di Carmignano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vin Santo di Montepulciano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vino Nobile di Montepulciano DOCG', '', '');
INSERT INTO region_area (SELECT 66, i FROM generate_series(696, 754) as i);

-- Italy/Trentino-Alto Adige
INSERT INTO area (name, description, weblink) VALUES ('Trentino-Alto Adige', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Alto Adige / Südtirol DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Casteller DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lago di Caldaro / Caldaro / Kalterersee / Kalterer DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Mitterberg IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Teroldego Rotaliano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Trentino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Trento DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valdadige / Etschtaler DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valdadige Terradeiforti / Terradeiforti DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vallagarina IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vigneti delle Dolomiti / Weinberg Dolomiten IGT', '', '');
INSERT INTO region_area (SELECT 67, i FROM generate_series(755, 766) as i);
-- INSERT INTO area (name, description, weblink) VALUES ('Delle Venezie DOC', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('IGP Trevenezie', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('IGP delle Venezie', '', '');
INSERT INTO region_area (region_id, area_id) VALUES (67, 391);
INSERT INTO region_area (region_id, area_id) VALUES (67, 405);
INSERT INTO region_area (region_id, area_id) VALUES (67, 392);

-- Italy/Umbria
INSERT INTO area (name, description, weblink) VALUES ('Umbria', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Allerona IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Amelia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Assisi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bettona IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Cannara IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Altotiberini DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Martani DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Perugini DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli del Trasimeno / Trasimeno DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lago di Corbara DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montefalco DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montefalco Sagrantino DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Narni IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Rosso Orvietano / Orvietano Rosso DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Spello IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Spoleto DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Todi DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Torgiano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Torgiano Rosso Riserva DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Umbria IGT', '', '');
INSERT INTO region_area (SELECT 68, i FROM generate_series(767, 787) as i);
-- INSERT INTO area (name, description, weblink) VALUES ('Orvieto DOC', '', '');
INSERT INTO region_area (region_id, area_id) VALUES (68, 437);

-- Italy/Valle d’Aosta
INSERT INTO area (name, description, weblink) VALUES ('Valle d’Aosta', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valle d’Aosta / Vallée d’Aoste DOC', '', '');
INSERT INTO region_area (SELECT 69, i FROM generate_series(788, 789) as i);

-- Italy/Veneto
INSERT INTO area (name, description, weblink) VALUES ('Veneto', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Amarone della Valpolicella DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Arcole DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Asolo Prosecco DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bagnoli Friularo / Friularo di Bagnoli DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bagnoli di Sopra / Bagnoli DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bardolino DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bardolino Superiore DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Bianco di Custoza / Custoza DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Breganze DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Berici DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Euganei DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Euganei Fior d’Arancio / Fior d’Arancio Colli Euganei DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli Trevigiani IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Colli di Conegliano DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Conegliano Valdobbiadene Prosecco DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Conselvano IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Corti Benedettine del Padovano DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Gambellara DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Lessini Durello / Durello Lessini DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Marca Trevigiana IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Merlara DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montello Rosso / Montello DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Montello–Colli Asolani DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Monti Lessini DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Piave DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Piave Malanotte / Malanotte del Piave DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Recioto della Valpolicella DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Recioto di Gambellara DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Recioto di Soave DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Riviera del Brenta DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Soave DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Soave Superiore DOCG', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valpolicella DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Valpolicella Ripasso DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Veneto IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Veneto Orientale IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Venezia DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Verona / Provincia di Verona / Veronese IGT', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vicenza DOC', '', '');
INSERT INTO area (name, description, weblink) VALUES ('Vigneti della Serenissima / Serenissima DOC', '', '');
INSERT INTO region_area (SELECT 70, i FROM generate_series(790, 830) as i);
-- INSERT INTO area (name, description, weblink) VALUES ('Delle Venezie DOC', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('Garda DOC', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('IGP Alto Livenza', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('IGP Trevenezie', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('IGP Vallagarina', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('IGP Vigneti delle Dolomiti / Weinberg Dolomiten', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('IGP delle Venezie', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('Lison DOCG', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('Lison-Pramaggiore DOC', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('Lugana DOC', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('Prosecco DOC', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('San Martino della Battaglia DOC', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('Valdadige / Etschtaler DOC', '', '');
-- INSERT INTO area (name, description, weblink) VALUES ('Valdadige Terradeiforti / Terradeiforti DOC', '', '');
INSERT INTO region_area (region_id, area_id) VALUES (70, 391);
INSERT INTO region_area (region_id, area_id) VALUES (70, 472);
INSERT INTO region_area (region_id, area_id) VALUES (70, 387);
INSERT INTO region_area (region_id, area_id) VALUES (70, 405);
INSERT INTO region_area (region_id, area_id) VALUES (70, 765);
INSERT INTO region_area (region_id, area_id) VALUES (70, 766);
INSERT INTO region_area (region_id, area_id) VALUES (70, 392);
INSERT INTO region_area (region_id, area_id) VALUES (70, 400);
INSERT INTO region_area (region_id, area_id) VALUES (70, 401);
INSERT INTO region_area (region_id, area_id) VALUES (70, 474);
INSERT INTO region_area (region_id, area_id) VALUES (70, 402);
INSERT INTO region_area (region_id, area_id) VALUES (70, 489);
INSERT INTO region_area (region_id, area_id) VALUES (70, 763);
INSERT INTO region_area (region_id, area_id) VALUES (70, 764);
