-- White
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Airen', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Albana', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Albarino', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Albarola', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Ansonica', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Arneis', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Asprinio', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Barbera Bianca', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Bellone', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Biancame', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Bianchetta Genovese', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Bianchetta Trevigiana', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Bianco di Alessano', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Biancolella', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Bombino Bianco', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Bosco', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Caprettone', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Carricante', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Catarratto', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Chardonnay', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Chenin Blanc', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Cococciola', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Coda di Volpe', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Cortese', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Damaschino', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Durella', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Erbaluce', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Falanghina', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Favorita', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Fiano', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Forastera', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Francavidda', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Friulano', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Garganega', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Gewürztraminer', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Girò', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Glera', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Grecanico Dorato', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Grechetto', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Greco', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Grillo', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Grüner Veltliner', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Guardavalle', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Guarnaccia', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Impigno', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Kerner', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Lumassina', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Maceratino', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Malvasia', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Manzoni Bianco', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Marsanne', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Marzemina Bianca', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Montonico Bianco', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Montù', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Mostosa', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Müller-Thurgau', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Muscat', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Nascetta', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Nasco', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Nosiola', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Nuragus', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Ortrugo', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pampanuto', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Passerina', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pecorello', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pecorino', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Petite Arvine', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Picolit', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pigato', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pignoletto', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pinella', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pinot Blanc', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pinot Grigio', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Prié Blanc', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Ribolla Gialla', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Riesling', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Rossese Bianco', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Roussanne', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Sauvignon Blanc', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Scimiscià', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Semidano', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Semillon', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Silvaner', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Spergola', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Timorasso', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Torbato', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Torrontes', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Trebbiano', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Verdeca', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Verdello', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Verdicchio', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Verduzzo', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Vermentino', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Vernaccia', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Vespaiola', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Viognier', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Vitovska', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Welschriesling', 'White', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Zibibbo', 'White', '', '', '');

-- Red
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Aglianico', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Albarossa', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Aleatico', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Alicante', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Alicante Bouschet', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Ancellotta', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Avanà', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Avarengo', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Barbera', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Barsaglina', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Becuet', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Bombino Nero', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Bonarda', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Bovale', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Brachetto', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Cabernet Franc', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Cabernet Sauvignon', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Cagnulari', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Canaiolo Nero', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Cannonau', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Carignano', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Carmenère', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Casavecchia', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Casetta', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Castiglione', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Cavrara', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Cesanese', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Chatus', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Ciliegiolo', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Corbina', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Cornalin', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Corvina', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Corvinone', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Croatina', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Dolcetto', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Doux d’Henry', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Fogarina', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Fortana', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Franconia', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Frappato', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Freisa', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Fumin', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Gaglioppo', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Gamaret', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Gamay', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Gamba Rossa', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Grechetto Rosso', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Greco Nero', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Grenache', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Grignolino', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Groppello', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Guarnaccia', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Lacrima', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Lagrein', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Lambrusca di Alessandria', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Lambrusco', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Magliocco Canino', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Malbec', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Malbo Gentile', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Malvasia Nera', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Marzemino', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Mayolet', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Merlot', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Molinara', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Mondeuse', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Monica', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Montepulciano', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Moscato Nero', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Moscato Rosa', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Nebbiolo', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Negroamaro', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Nerello Cappuccio', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Nerello Mascalese', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Neretta Cuneese', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Neretto di Bairo', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Nero Buono', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Nero d’Avola (Calabrese)', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Nocera', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Ottavianello', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pelaverga', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pelaverga Piccolo', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Perricone', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Petit Rouge', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Petit Verdot', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Piedirosso', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pignolo', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pinot Meunier', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pinot Noir', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Prié Rouge', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Primitivo', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Pugnitello', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Quagliano', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Raboso', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Rebo', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Recantina', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Refosco', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Rondinella', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Rossese', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Ruchè', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Sagrantino', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Sangiovese', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Schiava', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Schioppettino', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Sciascinoso', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Susumaniello', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Syrah', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Tai Rosso', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Tazzelenghe', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Tempranillo', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Teroldego', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Terrano', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Tintilia', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Turchetta', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Uva di Troia', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Uva Longanesi', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Uva Rara', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Vermentino Nero', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Vernaccia Nera', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Vespolina', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Vien de Nus', 'Red', '', '', '');
INSERT INTO grape (name, color, description, alternative_names, weblink) VALUES ('Vuillermin', 'Red', '', '', '');
